import { InterventionCandidate, ModalityVector } from '../models';

// ============================================
// Default Intervention Candidates
// Curated set for MVP
// ============================================

// Helper to generate UUID-like IDs
const id = (prefix: string, num: number) => `${prefix}-${num.toString().padStart(3, '0')}`;

// Default modality vectors for common activities
const modalities: Record<string, ModalityVector> = {
  breathing: {
    passiveActive: -0.5,
    novelFamiliar: -0.8,
    socialSolo: -1,
    finiteInfinite: -1,
    expressiveConsumptive: 0,
  },
  lookOutside: {
    passiveActive: -0.8,
    novelFamiliar: 0,
    socialSolo: -1,
    finiteInfinite: -1,
    expressiveConsumptive: -0.5,
  },
  readArticle: {
    passiveActive: -0.3,
    novelFamiliar: 0.5,
    socialSolo: -0.8,
    finiteInfinite: -0.5,
    expressiveConsumptive: -0.8,
  },
  textFriend: {
    passiveActive: 0.3,
    novelFamiliar: -0.3,
    socialSolo: 0.8,
    finiteInfinite: -0.5,
    expressiveConsumptive: 0.5,
  },
  stepOutside: {
    passiveActive: 0.3,
    novelFamiliar: 0,
    socialSolo: -0.5,
    finiteInfinite: -0.8,
    expressiveConsumptive: 0,
  },
  stretch: {
    passiveActive: 0.5,
    novelFamiliar: -0.5,
    socialSolo: -1,
    finiteInfinite: -1,
    expressiveConsumptive: 0.3,
  },
  journaling: {
    passiveActive: 0.3,
    novelFamiliar: 0,
    socialSolo: -1,
    finiteInfinite: -0.8,
    expressiveConsumptive: 0.9,
  },
  listenMusic: {
    passiveActive: -0.5,
    novelFamiliar: 0.3,
    socialSolo: -0.8,
    finiteInfinite: -0.5,
    expressiveConsumptive: -0.6,
  },
  walk: {
    passiveActive: 0.7,
    novelFamiliar: 0,
    socialSolo: -0.5,
    finiteInfinite: -0.8,
    expressiveConsumptive: 0,
  },
  sideProject: {
    passiveActive: 0.9,
    novelFamiliar: 0.5,
    socialSolo: -0.8,
    finiteInfinite: 0.5,
    expressiveConsumptive: 0.9,
  },
  callSomeone: {
    passiveActive: 0.4,
    novelFamiliar: -0.2,
    socialSolo: 1,
    finiteInfinite: -0.3,
    expressiveConsumptive: 0.5,
  },
  meditation: {
    passiveActive: -0.3,
    novelFamiliar: -0.5,
    socialSolo: -1,
    finiteInfinite: -1,
    expressiveConsumptive: 0,
  },
  tidySpace: {
    passiveActive: 0.6,
    novelFamiliar: -0.7,
    socialSolo: -1,
    finiteInfinite: -0.8,
    expressiveConsumptive: 0.3,
  },
  doodle: {
    passiveActive: 0.2,
    novelFamiliar: 0.3,
    socialSolo: -1,
    finiteInfinite: -0.5,
    expressiveConsumptive: 0.8,
  },
  podcast: {
    passiveActive: -0.6,
    novelFamiliar: 0.6,
    socialSolo: -0.5,
    finiteInfinite: 0,
    expressiveConsumptive: -0.9,
  },
  scrollSocial: {
    passiveActive: -0.8,
    novelFamiliar: 0.5,
    socialSolo: -0.3,
    finiteInfinite: 1,
    expressiveConsumptive: -0.9,
  },
};

export const DEFAULT_INTERVENTIONS: InterventionCandidate[] = [
  // Very Low Effort
  {
    id: id('int', 1),
    label: 'Take 3 deep breaths',
    description: 'A quick reset for your nervous system',
    modality: modalities.breathing,
    requiredEffort: 'very_low',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['mindful'],
    icon: 'leaf',
  },
  {
    id: id('int', 2),
    label: 'Look out a window',
    description: '30 seconds of distance gazing',
    modality: modalities.lookOutside,
    requiredEffort: 'very_low',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['mindful', 'restful'],
    icon: 'sunny',
  },
  {
    id: id('int', 3),
    label: 'Stand up and stretch',
    description: 'Quick body check-in',
    modality: modalities.stretch,
    requiredEffort: 'very_low',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['active'],
    icon: 'body',
  },

  // Low Effort
  {
    id: id('int', 4),
    label: 'Read a saved article',
    description: 'Something you bookmarked for later',
    modality: modalities.readArticle,
    requiredEffort: 'low',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['learner'],
    icon: 'document-text',
  },
  {
    id: id('int', 5),
    label: 'Text a friend',
    description: 'Send a quick check-in message',
    modality: modalities.textFriend,
    requiredEffort: 'low',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['connected'],
    icon: 'chatbubble',
  },
  {
    id: id('int', 6),
    label: 'Step outside briefly',
    description: 'Fresh air and a change of scenery',
    modality: modalities.stepOutside,
    requiredEffort: 'low',
    contextConstraints: [{ type: 'location', value: 'home', operator: 'equals' }],
    surface: 'off_phone',
    identityTags: ['active', 'mindful'],
    icon: 'walk',
  },
  {
    id: id('int', 7),
    label: 'Do a quick tidy',
    description: 'Clear one small area around you',
    modality: modalities.tidySpace,
    requiredEffort: 'low',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['builder'],
    icon: 'sparkles',
  },

  // Medium Effort
  {
    id: id('int', 8),
    label: '5-minute stretch routine',
    description: 'Simple stretches for your whole body',
    modality: modalities.stretch,
    requiredEffort: 'medium',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['active'],
    icon: 'fitness',
  },
  {
    id: id('int', 9),
    label: 'Write in notes app',
    description: 'Journal a thought or reflect briefly',
    modality: modalities.journaling,
    requiredEffort: 'medium',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['creative', 'mindful'],
    icon: 'create',
  },
  {
    id: id('int', 10),
    label: 'Listen to one song mindfully',
    description: 'Put on headphones and really listen',
    modality: modalities.listenMusic,
    requiredEffort: 'medium',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['restful', 'creative'],
    icon: 'musical-notes',
  },
  {
    id: id('int', 11),
    label: '5-minute meditation',
    description: 'Brief guided or unguided practice',
    modality: modalities.meditation,
    requiredEffort: 'medium',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['mindful', 'restful'],
    icon: 'flower',
  },
  {
    id: id('int', 12),
    label: 'Doodle or sketch',
    description: 'Let your hand wander on paper',
    modality: modalities.doodle,
    requiredEffort: 'medium',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['creative'],
    icon: 'brush',
  },
  {
    id: id('int', 13),
    label: 'Call someone you care about',
    description: 'A quick voice call to connect',
    modality: modalities.callSomeone,
    requiredEffort: 'medium',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['connected'],
    icon: 'call',
  },

  // High Effort
  {
    id: id('int', 14),
    label: 'Go for a 10-minute walk',
    description: 'Get your body moving outside',
    modality: modalities.walk,
    requiredEffort: 'high',
    contextConstraints: [],
    surface: 'off_phone',
    identityTags: ['active', 'mindful'],
    icon: 'walk',
  },
  {
    id: id('int', 15),
    label: 'Work on a side project',
    description: 'Make progress on something you care about',
    modality: modalities.sideProject,
    requiredEffort: 'high',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['builder', 'learner', 'creative'],
    icon: 'rocket',
  },
  {
    id: id('int', 16),
    label: 'Listen to a podcast episode',
    description: 'Learn something new while you move',
    modality: modalities.podcast,
    requiredEffort: 'high',
    contextConstraints: [],
    surface: 'on_phone',
    identityTags: ['learner'],
    icon: 'headset',
  },
];

// The "default behavior" modality - what social media scrolling looks like
export const SOCIAL_MEDIA_MODALITY: ModalityVector = modalities.scrollSocial;

export default DEFAULT_INTERVENTIONS;
